# Generated by Django 5.2.14 on 2026-05-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_doctor_id_alter_empleado_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
